<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>System.Reflection.Cache.Tests</RootNamespace>
		<AssemblyName>System.Reflection.Cache.Tests</AssemblyName>
		<IsPackable>false</IsPackable>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\System.Reflection.Cache\Cache.csproj" />
	</ItemGroup>
</Project>
